### PR TITLE
Remove output path

### PR DESCRIPTION
**Pull request by veeramarni**

### CODE REVIEW

**Comment by larixer** [comment]
@veeramarni Thanks, could you explain a bit why do you want to remove it?

**Comment by larixer** [comment]
I think the fix should be different, it is not to remove the output path in dev mode, but rather to not include clean-webpack-plugin in dev mode

**Comment by veeramarni** [comment]
@larixer I was wondering about the need for hardcoded value? It took me few hours to troubleshoot the issue and the `verbose` shows the current build dir location and not showing that it was getting set to `/` in the config file 

The issue is, clean webpack start scanning from `/` which eventually get fail due to permissions issue since `root` has privilege folders. 

image

Even in non-dev mode, it will fail as it scans from the wrong folder. 
If the need to push `/` in `output.path` then should be it passed from the custom configuration?

**Comment by larixer** [comment]
@veeramarni The value is set to `/` for dev mode only, it is required in order for `webpack-dev-server` to work properly. Why use `clean-webpack-plugin` when `webpack-dev-server` is running? it should not be used

**Comment by veeramarni** [comment]
Ok, should i change the condition like this `if (zen.dev && builder.require.probe('clean-webpack-plugin')) ` [here](https://github.com/sysgears/larix/blob/master/packages/zen/src/plugins/WebpackPlugin.ts#L73) ?

**Comment by larixer** [comment]
Thank you, looks good!

**Comment by larixer** [comment]
@veeramarni Published `@larix/zen@0.1.36` with your changes, thank you again!

**Pull request merged**
